# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A Fractal Life
description: >- # this means to ignore newlines until "baseurl:"
  A random walk through tech, design, math and other such nonsense.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://desaisid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
skin: "/assets/css/skins/light.css"
twitter:
  username: biased_coin

# Taxonomy pages
category_archive_path: "/categories/#"

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/


# Front Matter Defaults
#defaults:
#  # Post defaults
#  - scope:
#      path: "_posts"
#      type: posts
#    values:
#      layout: post
#      comments: false
#      share: true

footer_links:
  - title: Twitter
    url: https://twitter.com/biased_coin
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://in.linkedin.com/in/siddharthdesai
    icon: fab fa-linkedin
